on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: CI

jobs:
    static-analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  ini-values: memory_limit=-1
                  tools: composer:v2

            - name: Composer install
              run: composer install

            - name: Analyse
              run: make lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  ini-values: memory_limit=-1
                  tools: composer:v2

            - name: Composer install
              run: composer install

            - name: Unit Tests
              run: make test-unit

            - name: Functional Tests
              run: make test-functional
